import { Service } from '../models';

export interface Host {
    hostName: string;
    ipAddress: string;
    name: string;
    plugin_output: string;
    long_plugin_output: string;
    perf_data: string;
    status: number;
    last_update: number;
    has_been_checked: boolean;
    should_be_scheduled: boolean;
    current_attempt: number;
    max_attempts: number;
    last_check: number;
    next_check: number;
    check_options: number;
    check_type: number;
    last_state_change: number;
    last_hard_state_change: number;
    last_hard_state: number;
    last_time_up: number;
    last_time_down: number;
    last_time_unreachable: number;
    state_type: number;
    last_notification: number;
    next_notification: number;
    no_more_notifications: boolean;
    notifications_enabled: boolean;
    problem_has_been_acknowledged: boolean;
    acknowledgement_type: number;
    current_notification_number: number;
    accept_passive_checks: boolean;
    event_handler_enabled: boolean;
    checks_enabled: boolean;
    flap_detection_enabled: boolean;
    is_flapping: boolean;
    percent_state_change: number;
    latency: number;
    execution_time: number;
    scheduled_downtime_depth: number;
    process_performance_data: boolean;
    obsess: boolean;
    services: Service [];
    servicePassCount: number;
    serviceFailCount: number;
    showDetails: boolean;
}
